### ISSUE TITLE
ros2 profile run_tests crashes

### ISSUE THREAD

**Issue by cwecht** [safe-ros/ros2_profiling#8]
If I run `ros2 profile run_test ~/.ros/profile/reference_system-20230207090755/ ./src/ros2_profiling/ros2_profiling_demo/test/test_profile.py` in a docker container based on this dockerfile:

`FROM osrf/ros:humble-desktop

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
  lttng-tools liblttng-ust-dev \
  python3-babeltrace python3-lttng \
  lttng-modules-dkms \
  ros-humble-mcap-vendor \
  python3-pip

RUN pip install mcap-ros2-support pandas
`
For doing that I also had to
- go back to the humble Branch in ros2_tracing
- disable kernel profiling in ros2profile
![grafik](https://user-images.githubusercontent.com/20225760/217209679-e197d18c-1070-448c-b6c4-821e5f517b65.png)

The is the error I'm getting:
![grafik](https://user-images.githubusercontent.com/20225760/217206125-da5f7904-84e9-4647-ab8f-c4f20f2fdb5f.png)

I'm getting this warning during the build of cyclonedds though. Maybe this issue is related:
![tracing-warning](https://user-images.githubusercontent.com/20225760/217206383-5988d500-3e10-4a73-8308-92ac6d3d2bdd.PNG)

**Comment by mjcarroll** [comment]
> I'm getting this warning during the build of cyclonedds though. Maybe this issue is related:

This should be resolved by following https://github.com/safe-ros/ros2_profiling/pull/10

**Comment by mjcarroll** [comment]
The type issue with run_tests should be addressed as part of https://github.com/safe-ros/ros2_profiling/pull/11

**Comment by mjcarroll** [comment]
Note that the launch command syntax has slightly changed to take a launch file and a config file.

**Comment by cwecht** [comment]
Yep, with #11 the tests only fail because of asserts.
